weight:
  master: 50
  experimental: 50

replicas: 1

labels:
  name: microservice-2
  app: microservice-2

image:
  name: microservice-2
  master: beppev/IMAGE-NAME:MASTER
  experimental: beppev/IMAGE-NAME:VERSION

